"""empty message

Revision ID: 117a0ff24ae6
Revises: 
Create Date: 2025-03-09 18:20:11.555324

"""

from alembic import op
import sqlalchemy as sa
from fastapi_storages.integrations.sqlalchemy import ImageType


# revision identifiers, used by Alembic.
revision = '117a0ff24ae6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'car_reviews',
        sa.Column('car_id', sa.Uuid(), nullable=False),
        sa.Column('author_id', sa.Uuid(), nullable=False),
        sa.Column('score', sa.Numeric(), nullable=False),
        sa.Column('description', sa.String(), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_car_reviews')),
    )
    op.create_index(op.f('ix_car_reviews_id'), 'car_reviews', ['id'], unique=True)
    op.create_table(
        'user_reviews',
        sa.Column('user_id', sa.Uuid(), nullable=False),
        sa.Column('author_id', sa.Uuid(), nullable=False),
        sa.Column('score', sa.Numeric(), nullable=False),
        sa.Column('description', sa.String(), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_user_reviews')),
    )
    op.create_index(op.f('ix_user_reviews_id'), 'user_reviews', ['id'], unique=True)
    op.create_table(
        'car_review_likes',
        sa.Column('car_review_id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.Uuid(), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(
            ['car_review_id'], ['car_reviews.id'], name=op.f('fk_car_review_likes_car_review_id_car_reviews')
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_car_review_likes')),
    )
    op.create_index(op.f('ix_car_review_likes_id'), 'car_review_likes', ['id'], unique=True)
    op.create_table(
        'car_review_replies',
        sa.Column('car_review_id', sa.UUID(), nullable=False),
        sa.Column('description', sa.String(), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(
            ['car_review_id'], ['car_reviews.id'], name=op.f('fk_car_review_replies_car_review_id_car_reviews')
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_car_review_replies')),
        sa.UniqueConstraint('car_review_id', name=op.f('uq_car_review_replies_car_review_id')),
    )
    op.create_index(op.f('ix_car_review_replies_id'), 'car_review_replies', ['id'], unique=True)
    op.create_table(
        'user_review_likes',
        sa.Column('user_review_id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.Uuid(), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(
            ['user_review_id'], ['user_reviews.id'], name=op.f('fk_user_review_likes_user_review_id_user_reviews')
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_user_review_likes')),
    )
    op.create_index(op.f('ix_user_review_likes_id'), 'user_review_likes', ['id'], unique=True)
    op.create_table(
        'user_review_replies',
        sa.Column('user_review_id', sa.UUID(), nullable=False),
        sa.Column('description', sa.String(), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(
            ['user_review_id'], ['user_reviews.id'], name=op.f('fk_user_review_replies_user_review_id_user_reviews')
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_user_review_replies')),
        sa.UniqueConstraint('user_review_id', name=op.f('uq_user_review_replies_user_review_id')),
    )
    op.create_index(op.f('ix_user_review_replies_id'), 'user_review_replies', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_review_replies_id'), table_name='user_review_replies')
    op.drop_table('user_review_replies')
    op.drop_index(op.f('ix_user_review_likes_id'), table_name='user_review_likes')
    op.drop_table('user_review_likes')
    op.drop_index(op.f('ix_car_review_replies_id'), table_name='car_review_replies')
    op.drop_table('car_review_replies')
    op.drop_index(op.f('ix_car_review_likes_id'), table_name='car_review_likes')
    op.drop_table('car_review_likes')
    op.drop_index(op.f('ix_user_reviews_id'), table_name='user_reviews')
    op.drop_table('user_reviews')
    op.drop_index(op.f('ix_car_reviews_id'), table_name='car_reviews')
    op.drop_table('car_reviews')
    # ### end Alembic commands ###
